(require :conf.pkgs.cmp)
(require :conf.pkgs.lspconfig)
(require :conf.pkgs.treesitter)
(require :conf.pkgs.dap)
(require :conf.pkgs.venn)
(require :conf.pkgs.gitsigns)
(require :conf.pkgs.oil)
(require :conf.pkgs.lint)
(require :conf.pkgs.lualine)
(require :conf.pkgs.go)
(require :conf.pkgs.luasnip)
;; (require :conf.pkgs.lsp_lines)
;; (require :conf.pkgs.null-ls)
