(require :conf.pkgs.cmp)
(require :conf.pkgs.lspconfig)
(require :conf.pkgs.treesitter)
(require :conf.pkgs.dap)
(require :conf.pkgs.venn)
(require :conf.pkgs.gitsigns)
;; (require :conf.pkgs.lsp_lines)
;; (require :conf.pkgs.null-ls)
