(require :conf.pkgs.cmp)

;; (require :conf.pkgs.null-ls)
;; (require :conf.pkgs.lspconfig)
(require :conf.pkgs.treesitter)
(require :conf.pkgs.tree-sitter-context)
;; (require :conf.pkgs.conjure)
;; (require :conf.pkgs.test)
;; (require :conf.pkgs.lsp_lines)
;; (require :conf.pkgs.dap)
;; (require :conf.pkgs.heirline)
;; (require :conf.pkgs.gitsigns)
;; (require :conf.pkgs.harpoon)
;; (require :conf.pkgs.venn)
