keys:
  - &ivi age10q9wse8dh0749ffj576q775q496pycucxlla9rjdq5rd7f4csyhqqrmkk0
creation_rules:
  - path_regex: secrets/[^/]+\.?(yaml|json|env|ini)?$
    key_groups:
    - age:
      - *ivi
  - path_regex: secrets/lemptop/[^/]+\.?(yaml|json|env|ini)?$
    key_groups:
    - age:
      - *ivi
