keys:
  - &ivi age10q9wse8dh0749ffj576q775q496pycucxlla9rjdq5rd7f4csyhqqrmkk0
  - &serber age1sjqz54u07jv9ykpmg6s5fqms2jqyxzdwf7q940veapqzuafzr5es9nnl2v
  - &pump age1tzsvgxaxwvh4874d977fk0z7ghm4mqpm0c80vhxft87dv46p5uesq7mk42
creation_rules:
  - path_regex: secrets/[^/]+\.?(yaml|json|env|ini)?$
    key_groups:
    - age:
      - *ivi
      - *serber
      - *pump
  - path_regex: secrets/lemptop/[^/]+\.?(yaml|json|env|ini)?$
    key_groups:
    - age:
      - *ivi
  - path_regex: secrets/serber/[^/]+\.?(yaml|json|env|ini)?$
    key_groups:
    - age:
      - *serber
      - *ivi
