#!/bin/bash
echo " Compiliiing ${@}"

error () {
    echo "$1"
    exit 1
}

case "${@}" in
    helm\ lint*)
        shift
        shift
        echo " \-> helm lint --set cluster=debug-cluster --strict --quiet --with-subcharts ${@}"
        helm lint --set cluster=debug-cluster --strict --quiet --with-subcharts ${@} | sed -u -E -e "s@$(basename ${PWD})/|error during tpl function execution for \".*\"@@g"
        ;;
    racket*)
        shift
        echo " \-> racket -l errortrace -t ${@}"
        racket -l errortrace -t ${@}
        ;;
    ansible-lint*)
        shift
        echo " \-> ansible-lint --profile production --write=all -qq --nocolor"
        ansible-lint --profile production --write=all -qq --nocolor ${@}
        ;;
    ansible-playbook*)
        shift
        echo " \-> ansible-playbook -e@<(pass)"
        ansible-playbook -b -e "{\"ansible_become_pass\":\"$PASSWORD\"}" ${@}
        ;;
    awx*)
        echo " \-> awx"
        awx "$@" | filter-ansi
        ;;
    *)
        echo "Nope. Not compiling that. ARGS: ${@}"
        ;;
esac
