#!@bash@/bin/bash
echo " Compiliiing ${@}"

error () {
    echo "$1"
    exit 1
}

case "${@}" in
    racket*)
        shift
        echo " \-> racket -l errortrace -t ${@}"
        racket -l errortrace -t ${@}
        ;;
    ansible-lint*)
        shift
        echo " \-> ansible-lint --profile production --write=all -qq --nocolor"
        ansible-lint --profile production --write=all -qq --nocolor ${@}
        ;;
    awx*)
        echo " \-> awx"
        awx "$@" | filter-ansi
        ;;
    *)
        echo "Nope. Not compiling that. ARGS: ${@}"
        ;;
esac
