#!/usr/bin/env bash
if [[ $(id -u) -ne 0 ]]; then
    echo "Should be run with sudo privileges"
    exit
fi
mkdir /run/systemd/system/nix-daemon.service.d/
cat << EOF >/run/systemd/system/nix-daemon.service.d/override.conf 
[Service]
Environment="http_proxy=$http_proxy"
Environment="https_proxy=$http_proxy"
Environment="all_proxy=$http_proxy"
EOF
systemctl daemon-reload
systemctl restart nix-daemon
