require("my.packages.oil")
-- require("my.packages.cmp")
require("my.packages.blink")
require("my.packages.lint")
require("my.packages.luasnip")
require("my.packages.dap")
require("my.packages.go")
-- require("conf.pkgs.lualine")
